AllCops:
  TargetRubyVersion: '2.5'

Metrics/BlockLength:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

# trailing commas after last item in array/hash
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false

# no, I really don't want to put //'s around %r{}s
Style/RegexpLiteral:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/DateTime:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false
Lint/RescueException:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false
