language: cpp
os:
  - linux
  #- osx
# the default precise linux container has gcc 4.6
sudo: required
dist: trusty
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
    - tcsh
script: |
  set -e
  if [[ -n ${ANCIENT_BASH+1} ]]; then
    VER="bash-${ANCIENT_BASH}"
    curl -sSLO "http://ftp.gnu.org/gnu/bash/${VER}.tar.gz"
    tar -xf "${VER}.tar.gz"
    cd "$VER"
    ./configure
    make -j
    export PATH="$(pwd):$PATH"
    cd ..
    bash --version
  fi
  if [[ $BATCH == true ]]; then
    echo -e "*** testing batch mode in Python version $PYVER ***\n"
    bash -x ./scripts/newinstall.sh -cb -${PYVER}
  else
    echo -e "*** testing interactive mode in Python version $PYVER ***\n"
    echo -e "yes\nyes" | bash -x ./scripts/newinstall.sh -c -${PYVER}
  fi
  echo -e "*** Testing initializaion of shell environment ***\n"
  case $MANGLER in
    tcsh)
      # csh_20110502-2ubuntu2_amd64.deb from ubuntu:trusty (travis) opens a new
      # shell interactive shell when passed--version
      tcsh --version
      tcsh -ec 'source loadLSST.csh && echo $EUPS_PKGROOT'
      ;;
    *)
      bash --version
      bash -ec 'source loadLSST.bash && echo $EUPS_PKGROOT'
      ;;
  esac
env:
  - BATCH=true PYVER="2"
  - BATCH=true PYVER="3"
  - BATCH=false PYVER="2"
  - BATCH=false PYVER="3"
  - BATCH=true PYVER="3" ANCIENT_BASH="3.2.57"
  - BATCH=false PYVER="3" ANCIENT_BASH="3.2.57"
  - MANGLER=tcsh BATCH=true PYVER="3"
matrix:
  # osx builds are often very slow to start due to high demand
  fast_finish: true
  #allow_failures:
  #  - os: osx
  include:
    - os: linux
      env:
      compiler:
      language: ruby
      rvm: '2.4'
      script: bundle exec rubocop && bundle exec rspec --format doc
branches:
  only:
  - master
notifications:
  email: false
