# -*- python -*-
#
import sys
from lsst.sconsUtils import env, targets
SConscript("FileFilter.SConscript")

targets["bin"] = env.FilterFilesInto("#bin", Split("switcheups style.py noI.py ptest.sh newinstall.sh"))
