name: Acceptance tests

on:
  - pull_request

jobs:

  macos-lsstinstall-matrix:
    strategy:
      matrix:
        shell: [bash, zsh]
        option: ["", "-B"]
        os: [macos-14, macos-latest]
        include:
        - os: macos-14
          devel: "/Applications/Xcode_14.3.app/Contents/Developer"
        - os: macos-latest
          devel: "/Applications/Xcode_15.3.app/Contents/Developer"
    name: macOS lsstinstall test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: dryrun unit tests
        run:  bash test-lsstinstall.bash
      - name: install test
        env:
          DEVELOPER_DIR: ${{ matrix.devel }}
        run: |
          mkdir stack
          cd stack
          ${{ matrix.shell }} -c \
            "../scripts/lsstinstall -T w_latest ${{ matrix.option }} && \
             source loadLSST.${{ matrix.shell }} && \
             eups distrib install -t w_latest base"


  centos-lsstinstall:
    strategy:
      matrix:
        container: ["almalinux:9", "ubuntu:latest"]
    name: Linux lsstinstall test
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      - name: install prereqs
        run: |
          if [ "${{ matrix.container }}" = "almalinux:9" ]; then
              dnf install -y diffutils
          elif [ "${{ matrix.container }}" = "ubuntu:latest" ]; then
              apt-get update
              apt-get install -y curl
          fi
      - name: dryrun unit tests
        run:  bash test-lsstinstall.bash
      - name: install test
        run: |
          mkdir stack
          cd stack
          ../scripts/lsstinstall -T w_latest
          . ./loadLSST.bash
          eups distrib install -t w_latest base

